version: "3"
services:
  mongo:
    image: "mongo:6.0.12"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db

  growpulse:
    image: "growpulse/growpulse:latest"
    depends_on:
      - mongo
    ports:
      - "3000:3000"
      - "3100:3100"
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/growpulse?authSource=admin

volumes:
  mongodb-data:
